#!/usr/bin/env python3
"""Standalone exact Frobenius hierarchy falsifiers A1--A7.
Generated by lane bundle_checker.py; no repository-helper dependency.
"""

# Bundled source: exact_core.py
"""Fresh standalone exact arithmetic; no imported project helpers or floats."""
from fractions import Fraction
from itertools import product


class Field:
    def __init__(self, name, p, base=None, modulus=None):
        self.name, self.p, self.base = name, p, base
        self.modulus = modulus
        self.degree = 1 if base is None else base.degree * (len(modulus) - 1)
        self.q = p ** self.degree
        self.add = [[self._add(a, b) for b in range(self.q)] for a in range(self.q)]
        self.mul = [[self._mul(a, b) for b in range(self.q)] for a in range(self.q)]
        self.neg = [next(b for b in range(self.q) if self.add[a][b] == 0)
                    for a in range(self.q)]
        self.trace = [self._trace(a) for a in range(self.q)]
        self.sigma = [self.power(a, p) for a in range(self.q)]

    def digits(self, a):
        if self.base is None:
            return [a]
        out = []
        for _ in self.modulus[:-1]:
            out.append(a % self.base.q)
            a //= self.base.q
        return out

    def encode(self, digits):
        return sum(x * self.base.q ** j for j, x in enumerate(digits))

    def _add(self, a, b):
        if self.base is None:
            return (a + b) % self.p
        return self.encode([self.base.add[x][y]
                            for x, y in zip(self.digits(a), self.digits(b))])

    def _mul(self, a, b):
        if self.base is None:
            return a * b % self.p
        k = len(self.modulus) - 1
        B = self.base
        c = [0] * (2 * k - 1)
        for i, x in enumerate(self.digits(a)):
            for j, y in enumerate(self.digits(b)):
                c[i + j] = B.add[c[i + j]][B.mul[x][y]]
        for i in range(2 * k - 2, k - 1, -1):
            for j in range(k):
                c[i - k + j] = B.add[c[i - k + j]][B.neg[B.mul[c[i]][self.modulus[j]]]]
        return self.encode(c[:k])

    def power(self, a, n):
        out = 1
        while n:
            if n & 1:
                out = self.mul[out][a]
            a = self.mul[a][a]
            n //= 2
        return out

    def _trace(self, a):
        out, x = 0, a
        for _ in range(self.degree):
            out = self.add[out][x]
            x = self.power(x, self.p)
        assert out < self.p, (self.name, a, out)
        return out

    def sub(self, a, b):
        return self.add[a][self.neg[b]]

    def prod(self, xs):
        out = 1
        for x in xs:
            out = self.mul[out][x]
        return out


def fields():
    f2, f3 = Field('F2', 2), Field('F3', 3)
    f4 = Field('F4', 2, f2, [1, 1, 1])
    f8 = Field('F8', 2, f2, [1, 1, 0, 1])
    f9 = Field('F9', 3, f3, [1, 0, 1])
    f16 = Field('F16', 2, f4, [2, 1, 1])
    return {f.name: f for f in [f2, f3, f4, f8, f9, f16]}


def relative_trace(K, E, embedding):
    inverse = {x: a for a, x in enumerate(embedding)}
    out = []
    for x in range(E.q):
        total, y = 0, x
        for _ in range(E.degree // K.degree):
            total = E.add[total][y]
            y = E.power(y, K.q)
        out.append(inverse[total])
    return out


def root_sum(p, exponents):
    """Exact sum of p-th roots in Q[zeta]/(1+...+zeta^(p-1))."""
    counts = [0] * p
    for e in exponents:
        counts[e % p] += 1
    return tuple(c - counts[-1] for c in counts[:-1])


class Mat:
    """Sparse rectangular rational matrix with exact arithmetic."""
    def __init__(self, rows, cols, entries=None):
        self.rows, self.cols = rows, cols
        self.data = {ij: Fraction(v) for ij, v in (entries or {}).items() if v}

    @classmethod
    def eye(cls, n):
        return cls(n, n, {(j, j): 1 for j in range(n)})

    @classmethod
    def unit(cls, n, i, j):
        return cls(n, n, {(i, j): 1})

    def __eq__(self, other):
        return (self.rows, self.cols, self.data) == (other.rows, other.cols, other.data)

    def __add__(self, other):
        assert (self.rows, self.cols) == (other.rows, other.cols)
        data = dict(self.data)
        for ij, v in other.data.items():
            data[ij] = data.get(ij, 0) + v
        return Mat(self.rows, self.cols, data)

    def __sub__(self, other):
        return self + other.scale(-1)

    def scale(self, scalar):
        return Mat(self.rows, self.cols, {ij: v * scalar for ij, v in self.data.items()})

    def __matmul__(self, other):
        if self.cols != other.rows:
            raise ValueError('matrix source/target mismatch')
        right = {}
        for (i, j), v in other.data.items():
            right.setdefault(i, []).append((j, v))
        data = {}
        for (i, k), a in self.data.items():
            for j, b in right.get(k, []):
                data[i, j] = data.get((i, j), 0) + a * b
        return Mat(self.rows, other.cols, data)

    def star(self):
        return Mat(self.cols, self.rows, {(j, i): v for (i, j), v in self.data.items()})

    def kron(self, other):
        return Mat(self.rows * other.rows, self.cols * other.cols,
                   {(i * other.rows + k, j * other.cols + l): a * b
                    for (i, j), a in self.data.items()
                    for (k, l), b in other.data.items()})

    def tr(self):
        assert self.rows == self.cols
        return sum(self.data.get((i, i), 0) for i in range(self.rows))


def inclusion_matrix(K, E, embedding):
    return Mat(E.q, K.q, {(x, a): 1 for a, x in enumerate(embedding)})


def fibre_matrix(K, E, trace):
    """Return numerator R and positive denominator square r: V=R/sqrt(r)."""
    return Mat(E.q, K.q, {(x, trace[x]): 1 for x in range(E.q)}), E.q // K.q


def basis_vectors(p, n):
    return list(product(range(p), repeat=n))

# Bundled source: hierarchy_probe.py
"""A5: exact operator tables and derivative-span hierarchy certificates.

No polynomial degree is supplied to the membership algorithm. It receives
only a root-exponent table extracted by Fourier conjugating a permutation.
For diagonal D_f, D_f X(a) D_f* has diagonal quotient
zeta^(f(x+a)-f(x)); Z(b) commutes. If every quotient belongs to C_(k-1),
then every conjugated Pauli does: right Pauli multiplication preserves every
hierarchy level. The filtration below spans ALL translation differences over
F_p at each stage. Its last nonzero layer must be constants; the next zero.
Thus this is a finite recursive upper certificate, not a polynomial fit.

The span optimization is sound for root-valued diagonal operators: sums of
exponent tables multiply diagonal operators, and each successive difference
is linear. It does not assert that unrestricted C_k is a group.
"""
from itertools import product
from fractions import Fraction
import numpy as np


def phase_from_fourier(c, F, d):
    """Compute all target-Fourier matrix blocks from the gate permutation."""
    table = {}
    p, q = F.p, F.q
    for controls in product(range(q), repeat=d):
        # Generate target permutation as a concrete basis action first.
        permutation = [F.add[z][F.prod(controls)] for z in range(q)]
        for y, u in product(range(q), repeat=2):
            phases = [(-F.trace[F.mul[y][permutation[z]]]
                       + F.trace[F.mul[u][z]]) % p for z in range(q)]
            entry = root_sum(p, phases)
            if y != u:
                c.check('A5-upper', entry == (0,) * (p - 1),
                        f'{F.name} d={d}: Fourier block has off-diagonal entry {(y,u)}')
            else:
                possible = [e for e in range(p) if entry == tuple(q * v for v in root_sum(p, [e]))]
                c.check('A5-upper', len(possible) == 1,
                        f'{F.name} d={d}: Fourier diagonal is not a p-th root')
                table[controls + (y,)] = possible[0]
    return table


def span(vectors, p):
    """Exact row basis over F_p; numpy is integer-only."""
    pivots, rows = [], []
    for vector in vectors:
        v = np.array(vector, dtype=np.int64, copy=True) % p
        for pivot, row in zip(pivots, rows):
            if v[pivot]:
                v = (v - v[pivot] * row) % p
        nz = np.flatnonzero(v)
        if len(nz):
            pivot = int(nz[0])
            v = v * pow(int(v[pivot]), -1, p) % p
            where = sum(j < pivot for j in pivots)
            pivots.insert(where, pivot)
            rows.insert(where, v)
    return rows


def translation_indices(F, states):
    indexes = {x: i for i, x in enumerate(states)}
    return np.array([[indexes[tuple(F.add[xj][aj] for xj, aj in zip(x, a))]
                      for x in states] for a in states], dtype=np.int64)


def filtration(F, values, shifts, target_level):
    layers, dimensions = [np.array(values, dtype=np.int64)], []
    for _ in range(target_level + 1):
        layers = span(((v[s] - v) % F.p for v in layers for s in shifts), F.p)
        dimensions.append(len(layers))
    return dimensions, layers


def a5(c, Fs):
    samples = [(Fs[name], d) for name in ['F2', 'F3'] for d in range(1, 5)]
    samples += [(Fs['F4'], d) for d in [1, 2, 3]]
    for F, d in samples:
        phase = phase_from_fourier(c, F, d)
        if d == 2:
            amplitude_phases = ([0] * len(phase) if c.red == 'interference-erase-phase'
                                else list(phase.values()))
            coefficients = tuple(Fraction(x, len(phase)) for x in root_sum(F.p, amplitude_phases))
            expected_amplitude = Fraction(2 * F.q - 1, F.q ** 2)
            c.check('A5-interference', coefficients ==
                    (expected_amplitude,) + (0,) * (F.p - 2),
                    f'{F.name}: coherent return amplitude {coefficients} != {expected_amplitude}')
            c.record(f'A5-{F.name}-coherent', {'amplitude': str(coefficients[0]),
                     'return_probability': str(coefficients[0] ** 2)})
        states = list(product(range(F.q), repeat=d + 1))
        values = np.array([phase[x] for x in states], dtype=np.int64)
        shifts = translation_indices(F, states)
        upper_values, upper_shifts = values, shifts
        if c.red == 'hierarchy-extra-register-term' and F.name == 'F2' and d == 2:
            # A real extra independent-register phase, higher additive degree.
            extended = list(product(range(2), repeat=d + 2))
            upper_values = np.array([(phase[x[:-1]] + F.prod(x)) % 2 for x in extended])
            upper_shifts = translation_indices(F, extended)
        dimensions, remaining = filtration(F, upper_values, upper_shifts, d + 1)
        c.check('A5-upper', not remaining,
                f'{F.name} d={d}: claimed C_{d+1} has nonzero order-{d+2} '
                f'difference space; dimensions={dimensions}')
        # Stronger report: check layer d+1 consists of constants and is nonzero.
        layer = [upper_values]
        layer_dims = []
        for depth in range(1, d + 2):
            layer = span(((v[s] - v) % F.p for v in layer for s in upper_shifts), F.p)
            layer_dims.append(len(layer))
        c.check('A5-upper', all(np.all(v == v[0]) for v in layer),
                f'{F.name} d={d}: final recursive quotient is not scalar')
        strict_values = values.copy()
        if c.red == 'hierarchy-delete-factor':
            # Erase one register dependence by holding that control at one.
            strict_values = np.array([phase[(1,) + x[1:]] for x in states], dtype=np.int64)
        derivative = strict_values
        index = {x: i for i, x in enumerate(states)}
        for register in range(d):
            step = [0] * (d + 1)
            step[register] = 1
            shift = shifts[index[tuple(step)]]
            derivative = (derivative[shift] - derivative) % F.p
        distinct = sorted(set(map(int, derivative)))
        c.check('A5-strict', len(distinct) > 1,
                f'{F.name} d={d}: observed d-fold separate-control difference '
                f'is constant {distinct}; cannot exclude C_{d}')
        trace_dual = next(x for x in range(F.q) if F.trace[x] != 0)
        final_step = (0,) * d + (trace_dual,)
        scalar = (derivative[shifts[index[final_step]]] - derivative) % F.p
        c.check('A5-strict', np.all(scalar == scalar[0]) and int(scalar[0]) != 0,
                f'{F.name} d={d}: final observed commutator is not a nontrivial scalar')
        c.record(f'A5-{F.name}-d{d}', {
            'hilbert_dimension': len(states), 'all_translation_count': len(shifts),
            'difference_space_dimensions': dimensions,
            'strict_control_difference_values': distinct,
            'final_scalar_exponent': int(scalar[0]), 'trace_dual_step': trace_dual,
            'certified_sample_level': d + 1,
        })

# Bundled source: process_probe.py
"""A7: exact rational/scaled-rational Kraus computations with retained types."""
from dataclasses import dataclass
from fractions import Fraction
from itertools import product


@dataclass(frozen=True)
class System:
    names: tuple
    dimension: int

    def tensor(self, other):
        return System(self.names + other.names, self.dimension * other.dimension)


@dataclass
class Kraus:
    source: System
    target: System
    numerator: Mat
    denominator_square: int = 1

    def typed(self):
        return (self.numerator.rows, self.numerator.cols) == (self.target.dimension, self.source.dimension)

    def effect(self):
        return (self.numerator.star() @ self.numerator).scale(Fraction(1, self.denominator_square))

    def apply(self, rho):
        return (self.numerator @ rho @ self.numerator.star()).scale(Fraction(1, self.denominator_square))

    def after(self, first):
        if first.target != self.source or not self.typed() or not first.typed():
            raise ValueError('typed Kraus source/target mismatch')
        return Kraus(first.source, self.target, self.numerator @ first.numerator,
                     self.denominator_square * first.denominator_square)

    def tensor(self, other):
        return Kraus(self.source.tensor(other.source), self.target.tensor(other.target),
                     self.numerator.kron(other.numerator),
                     self.denominator_square * other.denominator_square)


def system(F):
    return System((F.name,), F.q)


def decoder(K, E, S, den):
    P = (S @ S.star()).scale(Fraction(1, den))
    Q = Mat.eye(E.q) - P
    return {'s': Kraus(system(E), system(K), S.star(), den),
            'f': Kraus(system(E), system(E), Q)}, P, Q


def effects(branches, n):
    out = Mat(n, n)
    for k in branches.values():
        out = out + k.effect()
    return out


def pure_state(n, entries):
    column = Mat(n, 1, {(i, 0): v for i, v in entries.items()})
    density = column @ column.star()
    return density.scale(Fraction(1, density.tr()))


def choi_from_matrix_units(k):
    n, m = k.source.dimension, k.target.dimension
    answer = Mat(n * m, n * m)
    for i, j in product(range(n), repeat=2):
        answer = answer + Mat.unit(n, i, j).kron(k.apply(Mat.unit(n, i, j)))
    return answer


def choi_gram(k):
    n, m = k.source.dimension, k.target.dimension
    vector = Mat(n * m, 1, {(i * m + o, 0): value
                           for (o, i), value in k.numerator.data.items()})
    return (vector @ vector.star()).scale(Fraction(1, k.denominator_square))


def reset(k, rho):
    success = k.apply(rho)
    return success + Mat.eye(k.target.dimension).scale(
        Fraction(rho.tr() - success.tr(), k.target.dimension))


def a7(c, Fs):
    tensor_unit = System((), 1)
    for F in Fs.values():
        discard = {}
        for a in range(F.q):
            ket = Mat(F.q, 1, {(a, 0): 1})
            preparation = Kraus(tensor_unit, system(F), ket)
            c.check('A7-PREP', preparation.typed()
                    and preparation.effect() == Mat.eye(1)
                    and preparation.apply(Mat.eye(1)).tr() == 1,
                    f'{F.name}: basis preparation {a} is not normalized')
            discard[a] = Kraus(system(F), tensor_unit, ket.star())
        if c.red == 'discard-omit-bra':
            discard.pop(F.q - 1)
        c.check('A7-PREP', all(k.typed() for k in discard.values())
                and effects(discard, F.q) == Mat.eye(F.q),
                f'{F.name}: hidden discard bras {list(discard)} do not give identity effect')
        for i, j in product(range(F.q), repeat=2):
            rho = Mat.unit(F.q, i, j)
            output = Mat(1, 1)
            for bra in discard.values():
                output = output + bra.apply(rho)
            c.check('A7-PREP', output == Mat(1, 1, {(0, 0): rho.tr()}),
                    f'{F.name}: hidden basis-bra discard differs from ordinary trace on {(i,j)}')
        c.record(f'A7-{F.name}-preparation-discard', {
            'normalized_basis_preparations': F.q, 'hidden_discard_bras': len(discard),
            'ordinary_trace_matrix_units_checked': F.q ** 2,
            'discard_target_tensor_unit_dimension': 1})
    K, L, E = Fs['F2'], Fs['F4'], Fs['F16']
    first = inclusion_matrix(K, L, [0, 1])
    trace = relative_trace(K, L, [0, 1])
    fibre, fibre_den = fibre_matrix(K, L, trace)
    for mode, S, den in [('J', first, 1), ('V', fibre, fibre_den)]:
        branches, P, Q = decoder(K, L, S, den)
        if c.red == 'process-wrong-target':
            branches['s'].target = system(L)
        c.check('A7-types', all(k.typed() for k in branches.values()),
                f'{mode}: decoder success target does not match its rectangular Kraus shape')
        if c.red == 'instrument-double-success':
            branches['s'].numerator = branches['s'].numerator.scale(2)
        c.check('A7-CP', effects(branches, L.q) == Mat.eye(L.q),
                f'{mode}: retained success/failure effects do not sum to identity')
        c.check('A7-CP', (S.star() @ S).scale(Fraction(1, den)) == Mat.eye(K.q)
                and Q.star() == Q and Q @ Q == Q, f'{mode}: isometry/complement identities')
        c.check('A7-CP', Mat.eye(L.q) - branches['s'].effect() == Q.star() @ Q,
                f'{mode}: success TNI certificate is not Q*Q')
        for label, k in branches.items():
            c.check('A7-CP', choi_from_matrix_units(k) == choi_gram(k),
                    f'{mode}/{label}: Choi matrix differs from explicit positive rank-one Gram')
        col = Mat(L.q, 1, {(i, 0): v for (i, j), v in S.data.items() if j == 0})
        code = (col @ col.star()).scale(Fraction(1, den))
        complement = Q.scale(Fraction(1, Q.tr()))
        coherent = pure_state(L.q, {0: 1, 2: 1})
        states = {'mixed': Mat.eye(L.q).scale(Fraction(1, L.q)),
                  'code': code, 'complement': complement, 'coherent': coherent}
        probabilities = {}
        for name, rho in states.items():
            outputs = {tag: k.apply(rho) for tag, k in branches.items()}
            prob = outputs['s'].tr()
            c.check('A7-CP', rho.tr() == 1 and prob == (P @ rho).tr()
                    and sum(out.tr() for out in outputs.values()) == 1,
                    f'{mode}/{name}: ordinary trace Born probability')
            probabilities[name] = str(prob)
        c.check('A7-CP', probabilities == {'mixed': '1/2', 'code': '1',
                                          'complement': '0', 'coherent': '1/2'},
                f'{mode}: basis/coherent/mixed success sentinels {probabilities}')
        c.record(f'A7-{mode}-decoder', {'success_probabilities': probabilities,
                 'outcome_types': {'s': 2, 'f': 4}, 'choi_positive_gram': True})
        # Sequential retained histories: fail at E, fail later at L, or K success.
        if mode == 'J':
            S2, den2 = inclusion_matrix(L, E, list(range(4))), 1
        else:
            S2, den2 = fibre_matrix(L, E, relative_trace(L, E, list(range(4))))
        outer, _, _ = decoder(L, E, S2, den2)
        inner, _, _ = decoder(K, L, S, den)
        try:
            both = (outer['s'].after(inner['s']) if c.red == 'sequential-reverse'
                    else inner['s'].after(outer['s']))
        except ValueError:
            c.check('A7-tower', False, f'{mode}: reversed decoders cannot compose E->L->K')
        histories = {'first_fail': outer['f'],
                     'first_success_second_fail': inner['f'].after(outer['s']),
                     'both_success': both}
        c.check('A7-tower', effects(histories, E.q) == Mat.eye(E.q),
                f'{mode}: three-history tower instrument completeness')
        direct = Kraus(system(E), system(K), (S2 @ S).star(), den * den2)
        c.check('A7-tower', both.numerator == direct.numerator
                and both.denominator_square == direct.denominator_square,
                f'{mode}: direct/two-stage success amplitudes')
        for i, j in product(range(E.q), repeat=2):
            rho = Mat.unit(E.q, i, j)
            c.check('A7-tower', both.apply(rho) == direct.apply(rho),
                    f'{mode}: matrix-unit success composition {(i,j)}')
            c.check('A7-tower', reset(inner['s'], reset(outer['s'], rho)) == reset(direct, rho),
                    f'{mode}: auxiliary reset tower composition {(i,j)}')
        for wrong in [Kraus(system(K), system(L), S, den),
                      Kraus(System(('unrelated-F4',), 4), system(K), S.star(), den)]:
            rejected = False
            try:
                wrong.after(outer['s'])
            except ValueError:
                rejected = True
            c.check('A7-types', rejected, f'{mode}: illegal compositing was accepted')
        c.record(f'A7-{mode}-tower', {'history_target_dimensions':
                 {tag: k.target.dimension for tag, k in histories.items()},
                 'matrix_units_tested': E.q ** 2})
        # Independent tensor retains ordered labels and their different targets.
        parallel = {(a, b): ka.tensor(kb) for a, ka in branches.items() for b, kb in branches.items()}
        if c.red == 'parallel-collapse-outcomes':
            parallel[('s', 'f')] = parallel.pop(('f', 's'))
        c.check('A7-parallel', set(parallel) == set(product('sf', repeat=2)),
                f'{mode}: independent ordered outcome pair was collapsed: {list(parallel)}')
        c.check('A7-parallel', effects(parallel, 16) == Mat.eye(16),
                f'{mode}: tensor instrument not complete')
        rhoA, rhoB = states['coherent'], states['code']
        product_state = rhoA.kron(rhoB)
        entangled = pure_state(16, {0: 1, 10: 1})
        for (a, b), k in parallel.items():
            c.check('A7-parallel', k.typed() and k.effect() == branches[a].effect().kron(branches[b].effect()),
                    f'{mode}: tensor branch {(a,b)} type/effect')
            c.check('A7-parallel', k.apply(product_state) == branches[a].apply(rhoA).kron(branches[b].apply(rhoB)),
                    f'{mode}: independent branch product output {(a,b)}')
            c.check('A7-parallel', k.apply(entangled).tr() == (k.effect() @ entangled).tr(),
                    f'{mode}: entangled Born probability {(a,b)}')
            # Linearity extension to entangled inputs checked on all units.
            for i, j, u, v in product(range(4), repeat=4):
                left, right = Mat.unit(4, i, j), Mat.unit(4, u, v)
                c.check('A7-parallel', k.apply(left.kron(right)) ==
                        branches[a].apply(left).kron(branches[b].apply(right)),
                        f'{mode}: tensor map matrix-unit equality')
        c.check('A7-parallel', sum(k.apply(entangled).tr() for k in parallel.values()) == 1,
                f'{mode}: retained entangled total probability')
        c.record(f'A7-{mode}-parallel', {'outcome_target_dimensions':
                 {''.join(tag): k.target.dimension for tag, k in parallel.items()},
                 'entangled_probabilities': {''.join(tag): str(k.apply(entangled).tr())
                                             for tag, k in parallel.items()}})
    # Fourier covariance of the whole typed instrument, success AND failure.
    H4 = Mat(4, 4, {(y, x): (-1) ** L.trace[L.mul[x][y]]
                   for y, x in product(range(4), repeat=2)})
    H2 = Mat(2, 2, {(y, x): (-1) ** K.trace[K.mul[x][y]]
                   for y, x in product(range(2), repeat=2)})
    fourier4 = H4.scale(Fraction(1, 2))
    _, _, QJ = decoder(K, L, first, 1)
    _, _, QV = decoder(K, L, fibre, fibre_den)
    # Both sides of success equality have denominator sqrt(2).
    c.check('A7-Fourier', fibre.star() @ fourier4 == H2 @ first.star(),
            'Fourier-dual success branch V*F_E differs from F_K J*')
    failure = QJ if c.red == 'fourier-failure-original-code' else QV
    c.check('A7-Fourier', failure @ fourier4 == fourier4 @ QJ,
            'Fourier-dual failure branch Q_V F_E differs from F_E Q_J')
    c.record('A7-Fourier-instrument', {'success_denominator_square': 2,
             'success_and_failure_branch_equalities': True, 'target_dimensions': [2, 4]})
    # Auxiliary reset-completion boundary: distinct outputs, explicit state.
    js = decoder(K, L, first, 1)[0]['s']
    outside, inside = Mat.unit(4, 2, 2), Mat.unit(4, 0, 0)
    local = reset(js, outside).kron(reset(js, inside))
    global_reset = reset(js.tensor(js), outside.kron(inside))
    candidate = global_reset if c.red == 'reset-global-as-local' else local
    expected = Mat.eye(2).scale(Fraction(1, 2)).kron(Mat.unit(2, 0, 0))
    c.check('A7-boundary', candidate == expected and candidate != global_reset,
            'global reset erases the second successful output; it differs from independent local reset')
    c.record('A7-reset-boundary', {'local_diagonal': [str(local.data.get((i,i), 0)) for i in range(4)],
             'global_diagonal': [str(global_reset.data.get((i,i), 0)) for i in range(4)]})

# Bundled source: frobenius_hierarchy_check.py
#!/usr/bin/env python3
"""Independent finite falsifiers A1--A7; standard library and numpy only.

Run --red NAME for a preregistered mathematical data mutation (exit 1).
The --matrix mode runs every red first, then green, retaining diagnostics.
"""
import argparse
import json
import sys
from itertools import product
from fractions import Fraction



MUTATIONS = {
    'frob-one-label': 'A1-symplectic',
    'weyl-positive-sign': 'A1-Weyl',
    'code-phase-subfield': 'A2-code',
    'logical-momentum-inclusion': 'A2-logical',
    'relative-trace-projection': 'A3-transfer',
    'fourier-positive-kernel': 'A3-Fourier',
    'trace-fibre-unnormalized': 'A3-normalization',
    'multiplication-as-addition': 'A4-multiplication',
    'embedding-coefficient-swap': 'A4-embedding',
    'hierarchy-extra-register-term': 'A5-upper',
    'hierarchy-delete-factor': 'A5-strict',
    'interference-erase-phase': 'A5-interference',
    'frobenius-no-shear': 'A6-tower',
    'process-wrong-target': 'A7-types',
    'instrument-double-success': 'A7-CP',
    'sequential-reverse': 'A7-tower',
    'parallel-collapse-outcomes': 'A7-parallel',
    'reset-global-as-local': 'A7-boundary',
    'fourier-failure-original-code': 'A7-Fourier',
    'discard-omit-bra': 'A7-PREP',
}


class GateFailure(Exception):
    def __init__(self, gate, detail):
        self.gate, self.detail = gate, detail
        super().__init__(f'{gate}: {detail}')


class Checks:
    def __init__(self, red=None):
        self.red, self.counts, self.records = red, {}, {}

    def check(self, gate, condition, detail):
        self.counts[gate] = self.counts.get(gate, 0) + 1
        if not condition:
            raise GateFailure(gate, detail)

    def record(self, key, value):
        self.records[key] = value


def embeddings(F):
    return [(F[a], F[b], list(range(F[a].q))) for a, b in
            [('F2', 'F4'), ('F2', 'F8'), ('F2', 'F16'),
             ('F3', 'F9'), ('F4', 'F16')]]


def weyl(F, a, b, x, sign=-1):
    y = F.add[x][a]
    return y, sign * F.trace[F.mul[b][y]] % F.p


def a1(c, Fs):
    for F in Fs.values():
        q, p, A, M, T, S = F.q, F.p, F.add, F.mul, F.trace, F.sigma
        for a in range(1, q):
            c.check('A1-symplectic', any(T[M[a][b]] for b in range(q)),
                    f'{F.name}: degenerate trace pairing at {a}')
            c.check('A1-symplectic', F.power(a, q - 1) == 1,
                    f'{F.name}: table is not a field')
        for a, b, u, v in product(range(q), repeat=4):
            original = (T[M[a][v]] - T[M[u][b]]) % p
            sb, sv = (b, v) if c.red == 'frob-one-label' else (S[b], S[v])
            transformed = (T[M[S[a]][sv]] - T[M[S[u]][sb]]) % p
            c.check('A1-symplectic', transformed == original,
                    f'{F.name}: labels {(a,b,u,v)} give {original}->{transformed}')
        sign = 1 if c.red == 'weyl-positive-sign' else -1
        for a, b, x in product(range(q), repeat=3):
            y, phase = weyl(F, a, b, x, sign)
            sy, sphase = weyl(F, S[a], S[b], S[x], sign)
            c.check('A1-Weyl', (S[y], phase) == (sy, sphase),
                    f'{F.name}: Frobenius basis-action mismatch')
        # Full Weyl label pairs, with both zero and unit input sentinels.
        for a, b, u, v in product(range(q), repeat=4):
            for x in [0, 1]:
                y, ph1 = weyl(F, u, v, x, sign)
                z, ph2 = weyl(F, a, b, y, sign)
                want, ph3 = weyl(F, A[a][u], A[b][v], x, sign)
                actual = (ph1 + ph2) % p
                expected = (ph3 + T[M[a][v]]) % p
                c.check('A1-Weyl', z == want and actual == expected,
                        f'{F.name}: reference cocycle labels {(a,b,u,v,x)} '
                        f'phase {actual} != {expected}')
        c.record(F'A1-{F.name}', {'q': q, 'frobenius': S,
                                'trace': T, 'nondegenerate': True})


def a2(c, Fs):
    for K, E, emb in embeddings(Fs):
        T = relative_trace(K, E, emb)
        kernel = [b for b in range(E.q) if T[b] == 0]
        stabilizers = [b for b in range(E.q)
                       if all(E.trace[E.mul[b][x]] == 0 for x in emb)]
        chosen = emb if c.red == 'code-phase-subfield' and E.name == 'F8' else kernel
        support = [x for x in range(E.q)
                   if all(E.trace[E.mul[b][x]] == 0 for b in chosen)]
        c.check('A2-code', chosen == stabilizers and support == emb,
                f'{K.name}->{E.name}: stabilizers={chosen}, true={stabilizers}; '
                f'support={support}, expected={emb}')
        J = inclusion_matrix(K, E, emb)
        P = J @ J.star()
        c.check('A2-code', J.star() @ J == Mat.eye(K.q) and P @ P == P
                and P.tr() == K.q, f'{E.name}: projector/dimension')
        for x in range(E.q):
            roots = root_sum(E.p, [E.trace[E.mul[b][x]] for b in chosen])
            expected = (len(chosen) if x in emb else 0,) + (0,) * (E.p - 2)
            c.check('A2-code', roots == expected, f'{E.name}: projector phase average at {x}')
        for a, b, y in product(range(K.q), range(E.q), range(K.q)):
            physical = weyl(E, emb[a], b, emb[y])
            ly, lp = weyl(K, a, T[b], y)
            c.check('A2-logical', physical == (emb[ly], lp),
                    f'{K.name}->{E.name}: compressed Weyl action {(a,b,y)}')
        for logical in range(K.q):
            lift = emb[logical] if c.red == 'logical-momentum-inclusion' else T.index(logical)
            for y in range(K.q):
                got = E.trace[E.mul[lift][emb[y]]]
                want = K.trace[K.mul[logical][y]]
                c.check('A2-logical', got == want,
                        f'{K.name}->{E.name}: logical {logical}, lift {lift}, '
                        f'input {y}, phase {got} != {want}')
        for b, u in product(range(E.q), repeat=2):
            same_action = all(E.trace[E.mul[b][x]] == E.trace[E.mul[u][x]] for x in emb)
            c.check('A2-logical', same_action == (T[b] == T[u])
                    == (E.sub(b, u) in kernel), f'{E.name}: momentum quotient')
        c.record(f'A2-{K.name}->{E.name}', {'support': support,
                 'phase_stabilizers': stabilizers, 'trace_fibres':
                 [[b for b in range(E.q) if T[b] == a] for a in range(K.q)]})


def a3(c, Fs):
    for K, E, emb in embeddings(Fs):
        T = relative_trace(K, E, emb)
        if c.red == 'relative-trace-projection' and E.name == 'F4':
            T = [x % 2 for x in range(E.q)]
        for a, x in product(range(K.q), range(E.q)):
            left = E.trace[E.mul[emb[a]][x]]
            right = K.trace[K.mul[a][T[x]]]
            c.check('A3-transfer', left == right,
                    f'{K.name}->{E.name}: trace pairing {(a,x)} gives {left}!={right}')
            c.check('A3-transfer', T[E.mul[emb[a]][x]] == K.mul[a][T[x]],
                    f'{K.name}->{E.name}: relative trace linearity')
        c.check('A3-transfer', set(T) == set(range(K.q)), f'{E.name}: trace not onto')
        for x in range(E.q):
            c.check('A3-transfer', T[E.sigma[x]] == K.sigma[T[x]],
                    f'{E.name}: Frobenius trace equivariance')
        R, r = fibre_matrix(K, E, T)
        norm_square = 1 if c.red == 'trace-fibre-unnormalized' else r
        c.check('A3-normalization', (R.star() @ R).scale(Fraction(1, norm_square)) == Mat.eye(K.q),
                f'{K.name}->{E.name}: fibre denominator square {norm_square}, size {r}')
        for x, a in product(range(E.q), range(K.q)):
            sign = 1 if c.red == 'fourier-positive-kernel' and E.p == 3 else -1
            left = sign * E.trace[E.mul[x][emb[a]]] % E.p
            right = -K.trace[K.mul[T[x]][a]] % K.p
            c.check('A3-Fourier', left == right and E.q == r * K.q,
                    f'{K.name}->{E.name}: Fourier entry {(x,a)} '
                    f'phase {left}!={right}; squared normalizations {E.q},{r*K.q}')
        for x, y in product(range(E.q), repeat=2):
            entries = [(-E.trace[E.mul[x][z]] + E.trace[E.mul[y][z]]) % E.p
                       for z in range(E.q)]
            expected = (E.q if x == y else 0,) + (0,) * (E.p - 2)
            c.check('A3-Fourier', root_sum(E.p, entries) == expected,
                    f'{E.name}: Fourier orthogonality {(x,y)}')
        J = inclusion_matrix(K, E, emb)
        UE = Mat(E.q, E.q, {(E.sigma[x], x): 1 for x in range(E.q)})
        UK = Mat(K.q, K.q, {(K.sigma[x], x): 1 for x in range(K.q)})
        c.check('A3-transfer', UE @ J == J @ UK and UE @ R == R @ UK,
                f'{E.name}: isometry Frobenius covariance')
        for a in range(K.q):
            c.check('A3-transfer', E.trace[emb[a]] ==
                    (E.degree // K.degree * K.trace[a]) % E.p,
                    f'{E.name}: character restriction degree')
    K, L, E = Fs['F2'], Fs['F4'], Fs['F16']
    tLK = relative_trace(K, L, [0, 1])
    tEL = relative_trace(L, E, list(range(4)))
    tEK = relative_trace(K, E, [0, 1])
    c.check('A3-transfer', [tLK[tEL[x]] for x in range(16)] == tEK,
            'F2->F4->F16: trace transitivity')
    R1, r1 = fibre_matrix(K, L, tLK)
    R2, r2 = fibre_matrix(L, E, tEL)
    R3, r3 = fibre_matrix(K, E, tEK)
    c.check('A3-normalization', R2 @ R1 == R3 and r1 * r2 == r3,
            'F2->F4->F16: normalized trace-fibre composition')
    J1, J2, J3 = (inclusion_matrix(K, L, [0, 1]),
                   inclusion_matrix(L, E, list(range(4))), inclusion_matrix(K, E, [0, 1]))
    c.check('A3-transfer', J2 @ J1 == J3, 'F2->F4->F16: inclusion tower')
    orbits, unseen = [], set(range(4))
    while unseen:
        x, orbit = min(unseen), []
        while x not in orbit:
            orbit.append(x)
            unseen.remove(x)
            x = L.sigma[x]
        orbits.append(orbit)
    c.check('A3-transfer', len(orbits) == 3 and len(J1.data) == 2,
            'Frobenius invariant vectors versus subfield support')
    c.record('A3-tower', {'relative_trace_F16_F4': tEL, 'absolute_trace_F16': tEK,
             'fibre_denominator_squares': [r1, r2, r3], 'F4_frobenius_orbits': orbits,
             'character_restriction_F4_F2': [L.trace[x] for x in [0, 1]]})


def gate_map(F, d, red=None):
    states = list(product(range(F.q), repeat=d + 1))
    mapping = {}
    for state in states:
        inc = F.prod(state[:-1])
        if red == 'multiplication-as-addition' and d == 2:
            inc = F.add[state[0]][state[1]]
        mapping[state] = state[:-1] + (F.add[state[-1]][inc],)
    return mapping


def a4(c, Fs):
    for F in Fs.values():
        for d in ([1, 2, 3, 4] if F.q <= 3 else [1, 2, 3] if F.q == 4 else [1, 2]):
            M = gate_map(F, d, c.red)
            c.check('A4-multiplication', len(set(M.values())) == len(M),
                    f'{F.name}, d={d}: gate is not bijective')
            for state, output in M.items():
                inc = F.sub(output[-1], state[-1])
                c.check('A4-multiplication', inc == F.prod(state[:-1]),
                        f'{F.name}, d={d}: input {state}, increment {inc}, '
                        f'product {F.prod(state[:-1])}')
                fs = tuple(F.sigma[x] for x in state)
                c.check('A4-multiplication', M[fs] == tuple(F.sigma[x] for x in output),
                        f'{F.name}, d={d}: Frobenius covariance')
                c.check('A4-multiplication', F.sub(output[-1], F.prod(state[:-1])) == state[-1],
                        f'{F.name}, d={d}: subtraction inverse')
    for K, E, emb in embeddings(Fs):
        for d in [1, 2, 3]:
            MK = gate_map(K, d)
            for state, output in MK.items():
                physical = tuple(emb[x] for x in state)
                got = physical[:-1] + (E.add[physical[-1]][E.prod(physical[:-1])],)
                if c.red == 'embedding-coefficient-swap' and K.name == 'F4':
                    got = tuple((x % 4) * 4 + x // 4 for x in got)
                want = tuple(emb[x] for x in output)
                c.check('A4-embedding', got == want,
                        f'{K.name}->{E.name}, d={d}, state={state}: {got}!={want}')
    c.record('A4-F4->F16', {'embedding': list(range(4)),
             'a_times_a_in_F4': Fs['F4'].mul[2][2],
             'embedded_a_times_a_in_F16': Fs['F16'].mul[2][2],
             'tested_control_counts': [1, 2, 3]})


def a6(c, Fs):
    K, E = Fs['F4'], Fs['F16']
    formula, twice = [], []
    for x in range(16):
        a0, b0 = x % 4, x // 4
        aa, bb = K.mul[a0][a0], K.mul[b0][b0]
        shear = 0 if c.red == 'frobenius-no-shear' else K.mul[2][bb]
        got = K.add[aa][shear] + 4 * bb
        formula.append(got)
        c.check('A6-tower', got == E.mul[x][x],
                f'F16 element (a0,b0)=({a0},{b0}): formula={got}, square={E.mul[x][x]}')
        got2 = E.sigma[E.sigma[x]]
        want2 = K.add[a0][b0] + 4 * b0
        twice.append(got2)
        c.check('A6-tower', got2 == want2, f'F16 sigma^2 shear at {x}')
        c.check('A6-tower', E.power(x, 16) == x, f'F16 sigma^4 at {x}')
    c.check('A6-tower', any(twice[x] != x for x in range(16)), 'F16 exact order is below four')
    orbits, unseen = [], set(range(16))
    while unseen:
        x, orbit = min(unseen), []
        while x not in orbit:
            orbit.append(x)
            unseen.remove(x)
            x = twice[x]
        orbits.append(orbit)
    fixed_labels = [x for x in range(16) if twice[x] == x]
    c.check('A6-tower', len(orbits) == 10 and fixed_labels == list(range(4)),
            f'F16 sigma^2 invariant-vector dimension {len(orbits)}, fixed labels {fixed_labels}')
    c.record('A6-explicit', {'sigma': formula, 'sigma_squared': twice,
                           'order': 4, 'b_squared': E.mul[4][4],
                           'sigma_squared_orbits': orbits, 'fixed_basis_labels': fixed_labels})


def run(red=None):
    c, Fs = Checks(red), fields()
    try:
        for gate, probe in [('A1', a1), ('A2', a2), ('A3', a3), ('A4', a4),
                            ('A5', a5), ('A6', a6), ('A7', a7)]:
            if red is None or MUTATIONS[red].startswith(gate):
                probe(c, Fs)
    except GateFailure as exc:
        return {'status': 'FAIL', 'mutation': red, 'failed_gate': exc.gate,
                'diagnostic': exc.detail, 'counts': c.counts}
    return {'status': 'PASS', 'mutation': red, 'counts': c.counts, 'records': c.records}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--red', choices=MUTATIONS, nargs='?', const='frob-one-label')
    for mutation in MUTATIONS:
        parser.add_argument('--red-' + mutation, dest='red', action='store_const', const=mutation,
                            help='mutate data at ' + MUTATIONS[mutation])
    parser.add_argument('--matrix', action='store_true', help='run all red probes before green')
    args = parser.parse_args()
    if args.matrix:
        results = []
        for mutation, intended in MUTATIONS.items():
            result = run(mutation)
            result['intended_gate'] = intended
            result['intended_failure_observed'] = result['status'] == 'FAIL' and result['failed_gate'] == intended
            results.append(result)
            print(json.dumps(result, sort_keys=True), flush=True)
        green = run()
        print(json.dumps(green, sort_keys=True), flush=True)
        return 0 if all(r['intended_failure_observed'] for r in results) and green['status'] == 'PASS' else 1
    result = run(args.red)
    print(json.dumps(result, sort_keys=True))
    return 0 if result['status'] == 'PASS' else 1


if __name__ == '__main__':
    sys.exit(main())
