name = "ArithmeticQuantumMechanics"
uuid = "153a0210-f8bb-4d5c-a8b6-fe591b6cc79e"
authors = ["arithmetic-quantum-mechanics contributors"]
version = "0.1.0"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
