module ArithmeticQuantumMechanics

export project_root, run_bundle_path
export horizontal_edge_index, vertical_edge_index, star_edges, plaquette_edges
export PauliCheck, toric_code_checks, toric_code_stabilizers
export toric_code_check_projectors, symplectic_commutes, gf2_rank
export toric_boundary_one_rows, toric_boundary_two_columns
export toric_code_stabilizer_rank, toric_boundary_square_zero
export toric_cellular_supercharge_square_zero
export toric_supercharge_summary, toric_chain_ghost_unification_summary
export oriented_toric_boundary_matrices, matmul_modp, rank_modp
export css_symplectic_isotropic, symplectic_css_bridge_summary
export css_supercharge_dictionary_summary, steane_css_matrices
export qutrit_css_toy_matrices
export steane_molecular_summary, steane_binary_space_rows
export steane_cohomology_by_degree
export steane_clifford_morphism_summary, steane_clifford_morphism_rows
export steane_all_clifford_generator_summary, steane_all_clifford_generator_rows
export steane_ghost_gaussian_elementary_rows
export arithmetic_quantum_field_examples, arithmetic_quantum_field_summary_rows
export arithmetic_quantum_field_basis_rows
export p1_rational_point_labels, p1_od_basis_labels, p1_od_evaluation_matrix
export projective_line_sheaf_field_examples
export projective_line_sheaf_field_summary_rows
export projective_line_sheaf_field_basis_rows
export projective_line_stalk_rows
export finite_ring_database_source_preflight
export finite_ring_database_tool_preflight
export finite_ring_database_preflight
export finite_ring_database_schema_version
export finite_ring_database_prd_table_names
export finite_ring_database_schema_sql
export migrate_finite_ring_database_schema!
export finite_ring_database_canonical_json
export finite_ring_presentation_id
export finite_ring_certificate_id
export finite_ring_id
export finite_ring_quantization_id
export FiniteRingStructureConstants
export finite_ring_structure_constants
export finite_ring_zero, finite_ring_one, finite_ring_order
export finite_ring_add, finite_ring_neg, finite_ring_mul, finite_ring_elements
export finite_ring_characteristic_exact
export finite_ring_zero_ring, finite_ring_zn, finite_ring_prime_field
export finite_ring_dual_numbers, finite_ring_product, finite_ring_mvp_examples
export finite_ring_additive_invariant_factors, finite_ring_basic_invariants
export finite_ring_apply_generator_image_matrix
export finite_ring_verify_isomorphism_certificate
export finite_ring_find_isomorphism_certificate
export finite_ring_deduplicate_small_rings
export finite_ring_residue_quantization_record
export finite_ring_blocked_residue_quantization_record
export finite_ring_mvp_residue_quantization_records
export finite_ring_thickened_frobenius_quantization_record
export finite_ring_blocked_thickened_frobenius_quantization_record
export finite_ring_mvp_thickened_frobenius_quantization_records
export finite_ring_prime_field_weyl_matrix_materialization
export finite_ring_gap_small_ring_import_status
export finite_ring_quotient_constructor_status

include("ArithmeticQuantumMechanics/ToricCodeSupercharge.jl")
include("ArithmeticQuantumMechanics/SymplecticCssBridge.jl")
include("ArithmeticQuantumMechanics/SteaneSupercharge.jl")
include("ArithmeticQuantumMechanics/SteaneCliffordGroup.jl")
include("ArithmeticQuantumMechanics/ArithmeticQuantumFields.jl")
include("ArithmeticQuantumMechanics/ProjectiveLineSheafFields.jl")

"""
    project_root()

Return the absolute path to the repository root for this checkout.
"""
project_root() = normpath(joinpath(@__DIR__, ".."))

"""
    run_bundle_path(run)

Return the absolute path to `runs/<run>` without creating it.
"""
run_bundle_path(run::AbstractString) = joinpath(project_root(), "runs", run)

include("ArithmeticQuantumMechanics/FiniteRingDatabasePreflight.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseSchema.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseIds.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseStructures.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseConstructors.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseQuotientConstructors.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseInvariants.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseCertificates.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseDedup.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseQuantization.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseMatrixArtifacts.jl")
include("ArithmeticQuantumMechanics/FiniteRingDatabaseGapImporter.jl")

end
